### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by Rwantop** [Yurunsoft/YurunPHP#1]
请问我如果要一个工具类来放常用的函数，那这个类应该放在哪？怎么调用？

**Comment by Yurunsoft** [comment]
可以放在项目"根目录/Lib/"文件夹里，文件名以"类名.class.php"命名。类库目录路径可以通过在入口文件定义APP_LIB常量来设定

**Comment by Rwantop** [comment]
好的，谢谢
